# render.yaml
services:
  - type: web
    name: dr-now-backend
    env: node
    rootDir: backend
    buildCommand: npm install
    startCommand: node server.js
    envVars:
      - key: NODE_ENV
        value: production
      - key: PORT
        value: 7777 
      # - key: CLIENT_URL
      #   value: https://dr-now-frontend.onrender.com 
  - type: static_site
    name: dr-now-frontend
    rootDir: frontend
    buildCommand: npm run build
    publishPath: dist
    routes:
      - type: rewrite
        source: /*
        destination: /index.html
